# Generated by Django 4.1 on 2022-08-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_book_readers_alter_book_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookrelation',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Отлично'), (2, 'Хорошо'), (3, 'Неплохо'), (4, 'Плохо'), (5, 'Очень плохо')], null=True),
        ),
    ]
